###
# notify deployer about deployment
##

- name: Send notification message via Slack
  slack:
    token: "/T9FEFD309/BC1PYLQS1/ubiNd91ywVozkbG8VgTlvJNy"
    msg: 'Deploy of {{ fqdn }} completed!'
    channel: '#general'
    username: 'Ansible on {{ sub_app_dir }}'
    validate_certs: no
  delegate_to: localhost